### ISSUE TITLE
[BUG] Breeding causes players near the spawned egg to disconnect

### ISSUE THREAD

**Issue by gravelcookie** [Wyrmheart-Team/Dragon_Mounts_Remastered#8]
**Describe the bug**
When breeding dragons (in our case a Forst Dragon and a Nether Dragon), the players disconnected when the egg should spawn. Every player that wans to go near the chunk where the egg may be gets disconnected. 

**To Reproduce**
Breed dragons
Heart animation goes off
When the egg wants to spawn we get errors

Every person after that that want to go near gets disconnected as wenn
All other players on the server/world are not affected

**Additional context**
The first logs depicted an error with Embeddium/Iris/Monocle (because it says dragon egg renderer error) so I deactivated the mods. That lead to a different error code but the same results where given (players get disconnected because of the dragon egg renderer.

[latest.log](https://github.com/user-attachments/files/18048164/latest.log)
[crash-2024-12-06_22.14.12-client.txt](https://github.com/user-attachments/files/18048167/crash-2024-12-06_22.14.12-client.txt)

**Comment by Gaplon** [comment]
I have the same problem

**Comment by Horeak** [comment]
This issue will be fixed in the upcoming version which shouldn't be too far away.

For now you can find a patched version [Here](https://cdn.discordapp.com/attachments/1208177271400038492/1310374988217323641/Dragon_Mounts_Remastered-1.21.1-1.2.4.jar?ex=6755780e&is=6754268e&hm=76e32befbaceeb7066a6c6c4841ee30a02a3787b027667bc9572da5ea5c0ac39&)

**Comment by Gaplon** [comment]
Does that version work? Bc i got this error 
[crash-2024-12-07_14.41.06-server.txt](https://github.com/user-attachments/files/18048623/crash-2024-12-07_14.41.06-server.txt)

**Comment by Horeak** [comment]
It did work for someone with a similar issue, but seems that crash there is a new issue so ill look into it

**Comment by Gaplon** [comment]
Also you can check bc it crash when they are spawning in blocks etc.

**Comment by Gaplon** [comment]
I cant get the crash log rn

**Comment by Gaplon** [comment]
Also in the new patched version the hybrid system dont seem to work i always get basic dragon egg

**Comment by Gaplon** [comment]
Sorry that i spam so much i really like the mod

**Comment by Gaplon** [comment]
Okay i figured the last one, when you break the egg and place it again it turns into basic dragon egg if it stays in place its hybrid egg
